name: Test Local MI300X

on:
  workflow_dispatch:
    inputs:
      tp:
        description: 'Tensor Parallelism (1, 2, 4, or 8)'
        required: true
        default: '8'
        type: choice
        options:
          - '1'
          - '2'
          - '4'
          - '8'
      conc:
        description: 'Concurrency'
        required: true
        default: '16'
        type: choice
        options:
          - '4'
          - '8'
          - '16'
          - '32'
          - '64'
      isl:
        description: 'Input Sequence Length'
        required: true
        default: '1024'
        type: choice
        options:
          - '1024'
          - '8192'
      osl:
        description: 'Output Sequence Length'
        required: true
        default: '1024'
        type: choice
        options:
          - '1024'
          - '8192'
      run_eval:
        description: 'Run accuracy evaluation'
        required: false
        default: false
        type: boolean

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: 'mi300x-local_0'
      image: 'vllm/vllm-openai-rocm:v0.14.0'
      model: 'openai/gpt-oss-120b'
      model-prefix: 'gptoss'
      precision: 'fp4'
      framework: 'vllm'
      exp-name: 'gptoss'
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      tp: ${{ inputs.tp }}
      ep: '1'
      dp-attn: false
      max-model-len: '8192'
      conc: ${{ inputs.conc }}
      spec-decoding: 'none'
      disagg: 'false'
      run-eval: ${{ inputs.run_eval }}

  collect-results:
    needs: benchmark
    if: always()
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      result-prefix: "bmk"
